### ISSUE TITLE
Pls fix

### ISSUE THREAD

**Issue by moch09** [JGYTVevo/BossJG#1]
Skin bisa error

**Comment by moch09** [comment]
Skin boss error

**Comment by JGYTVevo** [comment]
send me a screenshot

**Comment by moch09** [comment]
Ok

**Comment by moch09** [comment]
How i upload file?

**Comment by XxMegaIS123xX** [comment]
Hello

**Comment by JGYTVevo** [comment]
You have to rename the skin you want to zeus.png then reload your server and it should be done!
i was testing this last night i will get my dev to add  a custom skin config.yml
i would not recomend doing this on github because it will delete the resaurce folder download this plugin as a .zip and then unzip it on your server hosting
